#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /admin/logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }