liip_imagine:
    resolvers:
        default:
            web_path: ~
        profile_photos:
            web_path:
              # use %kernel.project_dir%/web for Symfony prior to 4.0.0
              web_root: "%kernel.project_dir%/public"
              cache_prefix: "media/cache"

    filter_sets:
        cache: ~
        # the name of the "filter set"
        thumb:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [100, 70], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background: { size: [104, 74], position: center, color: '#dee2e6' }

        thumb_medium:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [300, 213], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background: { size: [304, 217], position: center, color: '#dee2e6' }

        thumb_dashboard_admin:
            quality: 75
            filters:
                thumbnail: { size: [232, 162], mode: outbound }