nelmio_api_doc:
    documentation:
        schemes: [http, https]
        info:
            title: App Fshigueru
            description: Doc api
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc