security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        admin:
            entity:
                class: App\Entity\Admin\User
        api:
            entity:
                class: App\Entity\Admin\User
                property: apiKey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:  ^/api
            provider: api
            stateless:  true
            logout:
                invalidate_session: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

        admin:
            pattern:  ^/admin
            anonymous: true
            provider: admin
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin
                always_use_default_target_path: true
            logout:
                invalidate_session: true
                path: /admin/logout
                target: /admin/login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 86400
                path:     /admin

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api, roles: ROLE_USER_API }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        App\Entity\Admin\User:
            algorithm: bcrypt
            cost: 12